Engine:
  Local:
    Bundles:
      - https://github.com/agnosticeng/ch-iceberg/releases/download/v0.0.5/ch-iceberg_0.0.5_{{ .RUST_TARGET | default "x86_64-unknown-linux-gnu" }}.tar.gz
      - https://github.com/agnosticeng/ch-stellar/releases/download/v0.0.9/ch-stellar_0.0.9_{{ .RUST_TARGET | default "x86_64-unknown-linux-gnu" }}.tar.gz
    Logging:
      DiscardSources:
        - AwsAuthSTSAssumeRoleWebIdentityCredentialsProvider
    Settings:
      send_logs_level: warning
      enable_named_columns_in_function_tuple: 1
      schema_inference_make_columns_nullable: auto
      remote_filesystem_read_prefetch: 0
      input_format_parquet_use_native_reader: 1
      output_format_arrow_string_as_string: 0
      max_execution_time: 3600
      enable_unaligned_array_join: 1

Includes:
  - ../common

DefaultVars:
  ICEBERG_SINK_TABLE_MARKER_FIELD: ledger_sequence
  ICEBERG_SINK_TABLE_ORDER_BY: ledger_sequence,transaction_id,operation_id,type

Init:
  Queries:
    - create_table#ignore-failure=true
    - init_from_table

Source:
  Query: galexie_source
  PollInterval: '{{ .SOURCE_POLL_INTERVAL | default "30s" }}'

Stages:
  - Execute:
      PoolSize: '{{ .FETCH_POOL_SIZE | default "4" }}'
      Ordered: true
      Queries:
        - changes_common_create_ledgers
        - changes_common_create_txs
        - create_range
        - changes_common_drop_ledgers
        - changes_common_drop_txs

  - Buffer:
      Enter: create_buffer_from_range
      Leave: rename_buffer
      Queries:
        - insert_range_into_buffer
        - drop_range
        - merge_range_and_buffer_vars
      MaxDuration: '{{ .MAX_BUFFER_DURATION | default "300s" }}'
      MaxRows: '{{ .MAX_BUFFER_ROWS | default "960000" }}'

  - Execute:
      PoolSize: 1
      Ordered: true
      Queries:
        - append_buffer_to_table
        - drop_buffer
      ClickhouseSettings:
        max_threads: 1
        max_insert_threads: 1
