Engine:
  Local:
    Bundles:
      - https://github.com/agnosticeng/ch-iceberg/releases/download/v0.0.2/ch-iceberg_0.0.2_{{ .RUST_TARGET | default "x86_64-unknown-linux-gnu" }}.tar.gz
      - https://github.com/agnosticeng/ch-stellar/releases/download/v0.0.4/ch-stellar_0.0.4_{{ .RUST_TARGET | default "x86_64-unknown-linux-gnu" }}.tar.gz 
    Logging:
      DiscardSources:
        - AwsAuthSTSAssumeRoleWebIdentityCredentialsProvider
    Settings:
      send_logs_level: warning
      enable_named_columns_in_function_tuple: 1
      schema_inference_make_columns_nullable: auto
      remote_filesystem_read_prefetch: 0
      input_format_parquet_use_native_reader: 1
      output_format_arrow_string_as_string: 0
      enable_unaligned_array_join: 1
      max_execution_time: 3600

Init:
  Queries:
    - create_table
    - init_start

Source:
  Query: source
  PollInterval: {{ .SOURCE_POLL_INTERVAL | default "30s" }}

Stages:
  - Execute:
      PoolSize: {{ .FETCH_POOL_SIZE | default "4" }}
      Ordered: true
      Queries:
        - create_ledgers
        - create_txs 
        - drop_ledgers
        - create_range 
        - check_txs
        - drop_txs

  - Buffer:
      Enter: create_buffer
      Leave: rename_buffer
      Queries:
        - insert_into_buffer
        - drop_range
        - merge_vars
      MaxDuration: {{ .MAX_BUFFER_DURATION | default "300s" }}
      MaxRows: {{ .MAX_BUFFER_ROWS | default "960000" }}

  - Execute: 
      PoolSize: 1
      Ordered: true
      Queries:
        - append_to_table
        - drop_buffer
      ClickhouseSettings:
        max_threads: 1
        max_insert_threads: 1